FROM public.ecr.aws/lambda/python:3.8

ENV PYTHONPATH "${PYTHONPATH}:/"
ENV PORT=8000

RUN pip install --upgrade pip

COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ./app ./app

COPY ./fallback_locales.csv /app/

CMD ["app.main.handler"]
