name: Build and empheria-PDP-api

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build using Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run linter [flake8]
        run: flake8 .

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.ENV_AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-2

      - name: Test with pytest
        run: |
          pytest

      # - name: run unit tests [pytest]
      #   env:
      #     ENV_AWS_ACCESS_KEY_ID: ${{ secrets.ENV_AWS_ACCESS_KEY }}
      #     ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}

      #   run: pytest.

      - name: Setup Terraform
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3

      - name: Terraform deploy
        if: github.ref == 'refs/heads/main'
        id: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ENV_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-2"
        run: |
          find . -name '*.pyc' -delete
          cd terraform/app-deploy
          terraform init
          terraform workspace list
          if [ ${GITHUB_REF##*/} == "main" ]; then terraform workspace select main; else terraform workspace select develop; fi
          terraform plan
          if [ ${GITHUB_REF##*/} == "main" ] || [ ${GITHUB_REF##*/} == "develop" ]; then terraform apply -auto-approve ; else echo "please check your feature branch plan and merge to develop branch to perform terraform apply"; fi
