name: Build and empheria-PDP-api

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build using Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run linter [flake8]
        run: flake8 .

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "eu-west-2"
          role-to-assume: "arn:aws:iam::601772211076:role/github-action-terraform-role"
          role-session-name: "GitHubActionsSession"

      - name: Test with pytest
        run: |
          pytest

      # - name: run unit tests [pytest]
      #   env:
      #     ENV_AWS_ACCESS_KEY_ID: ${{ secrets.ENV_AWS_ACCESS_KEY }}
      #     ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}

      #   run: pytest.

      - name: Setup Terraform
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3

      - name: Terraform deploy
        if: github.ref == 'refs/heads/main'
        id: deploy
        env:
          AWS_DEFAULT_REGION: "eu-west-2"
        run: |
          find . -name '*.pyc' -delete
          cd terraform/app-deploy
          terraform init
          terraform workspace select ${GITHUB_REF##*/} || terraform workspace new ${GITHUB_REF##*/}
          terraform plan
          terraform apply -auto-approve
